title: Developing Diary
description: 지킬 테스트
author: 현민
avatar: /logo.png
email: kevinxkim2023@gmail.com
url: "https://aksel26.github.io/"
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: Shangzhi Huang
  links:
    - https://github.com/aksel26
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko
